version: "3.9"

services:
  web:
    build: 
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    command: python3 add12.py
    environment: 
      - RABBIT_HOST=rabbitmq_container
      - DB_HOST=pg_db_container
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - rabbitmq_container
  rabbitmq_container:
    image: "rabbitmq:3.11.5-management"
    ports:
      - 5672:5672
      - 15672:15672
    hostname: rabbitmq_container
  celery_working:
    build: .
    command: celery -A celery_working worker --loglevel=info --pool=solo
    environment: 
      - RABBIT_HOST=rabbitmq_container
      - DB_HOST=pg_db_container
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  db:
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    hostname: pg_db_container